### ISSUE TITLE
Document IFC export settings to improve import process

### ISSUE THREAD

**Issue by pabloderen** [agviegas/web-ifc-viewer#42]
Testing with Revit OOB IFC export returns missing classes and parsing errors. Using IFC 2x3 CoordinationView_V2.0

`parse-process.js:24 Error while parsing item: ('http://www.csiorg.net/uniformat','1998',$,'Uniformat',$,$,$) of type FCCLASSIFICATION`

And one of these per each element in the IFC:

`parse-process.js:24 Error while parsing item: ('2UatwVAlX8_vRTau_vmt4$',#42,'OutPort_2547','Flow',$,#293908,$,.SOURCEANDSINK.,$,$) of type IFCDISTRIBUTIONPORT`

The process ends with:

![image](https://user-images.githubusercontent.com/14131475/109012386-b80a8f00-7690-11eb-9de4-23e301d83f6b.png)

What type of IFC exportation setting does the viewer support?

**Comment by agviegas** [comment]
Hi @pabloderen ! 
Right now I am helping develop an alternative parser for the library in WASM. It will take some time, but once made, this problem will be solved, as these errors are due to the library not being complete.

**Comment by agviegas** [comment]
Hey @pabloderen we have just updated the library. Can you try again with the current build and let us know how it goes?
