### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by babivillanova** [agviegas/web-ifc-viewer#48]
Hi!! Just got to know about the project.
I'm an architect from Brazil, 9 years BIM Manager in construction companies and designers offices.

I am just starting a Master in Adavanced Computation for Architecture and Design,  got to learn a few javascrip, and how to use three.js, mostly for grasshopper files (with the appserver). Probably can't help with the coding, but maybe testing.
I have a lot of IFC data, and I am very interested in watch the project development.

Please let me know if I could be of any help.

Tks!
Babi Villanova

**Comment by agviegas** [comment]
Hey, sounds great! Testing with a lot of models would definitely help us improve the library. Feel free to join the [discord channel](https://discord.gg/nvH9F55T) and let us know of your experiments. Also, feel free to open Issues to request new features, or even PRs if you want to get your feet wet with the code. 😀

**Comment by MenderBlender** [comment]
Hey, you discord link doesn't work. Can you renew it I have some questions?

**Comment by agviegas** [comment]
Hey, try [this one](https://discord.gg/SAyHYZ8j)!
