### ISSUE TITLE
Loading large IFC file crashes browser

### ISSUE THREAD

**Issue by Booli** [agviegas/web-ifc-viewer#52]
Hey,

super cool project! I was looking around for a BIM/IFC viewer and found you through google.

I, maybe ambitiously, loaded the famous 7 story hospital file: 
[Famous hospital IFC file](http://openifcmodel.cs.auckland.ac.nz/Model/Details/308 )

It showed up somewhere high "in the sky" of the model, but panning and zooming quickly crashed the browser and was really slow.

Can the project already handle these kind of files? Will it be able to handle them in a later stage?

**Comment by agviegas** [comment]
Hey, thanks! We are working to optimize the geometry, so the performance should get better this week. Regarding the position of the model, I have inspected it and it looks like the model is 165 m above the 0 level. Can you create a issue in the [web-ifc](https://github.com/tomvandig/web-ifc) repo to solve this?
![image](https://user-images.githubusercontent.com/56475338/114892091-bd709400-9e0c-11eb-83ca-60453ed3280b.png)

**Comment by Booli** [comment]
Hey,

Thanks for your comment. As far as I understand, the IFC coordination is meant to also place in the world. So I assume the building is normally elevated 165m above sea level? 

Might also that I am misunderstanding.

**Comment by agviegas** [comment]
Yes, that's correct! I didn't want to imply that the IFC is wrong. If you create an issue in the abovementioned repository, we will be able to track that and implement a solution for cases in which IfcSite contemplates the elevation of the building.
