### ISSUE TITLE
doesn't show buttons

### ISSUE THREAD

**Issue by MenderBlender** [agviegas/web-ifc-viewer#53]
![Schermafbeelding 2021-04-15 132235](https://user-images.githubusercontent.com/67467107/114861589-bdad6700-9ded-11eb-9e49-7888947f1a50.png)

When I open the index file I get just a blank output and I don't see the buttons on the left side. What should I do to fix this?
Thanks for helping :)

**Comment by MenderBlender** [comment]
yeah local

**Comment by agviegas** [comment]
What local server are you using to open the file?

**Comment by MenderBlender** [comment]
I just open it in a browser, i tried a different one but none of them works

**Comment by agviegas** [comment]
You can't open an HTML file in the browser directly, you need a local server.  Keep in mind that some basic HTML / Javascript knowledge is required to work with the library. [This](https://www.youtube.com/watch?v=qz0aGYrrlhU) is a good place to start!
