### ISSUE TITLE
Loaded model doesnt show what it is suposed to show

### ISSUE THREAD

**Issue by MenderBlender** [agviegas/web-ifc-viewer#54]
This is the image that it should display:
![afbeelding](https://user-images.githubusercontent.com/67467107/115007433-44277e80-9eaa-11eb-922d-8d5af8928a33.png)

This is what it displays: 
![afbeelding](https://user-images.githubusercontent.com/67467107/115007555-64573d80-9eaa-11eb-8480-32259a3b2316.png)

The file I use: 
[miniproject.zip](https://github.com/agviegas/web-ifc-viewer/files/6324121/miniproject.zip)

Thanks for helping me!

**Comment by agviegas** [comment]
You can open an issue in [web-ifc](https://github.com/tomvandig/web-ifc) to solve this!
