### ISSUE TITLE
Geometry view issue 

### ISSUE THREAD

**Issue by richardgush** [agviegas/web-ifc-viewer#59]
Hi Antonio, I converted one of the Revit example files to ifc and there is a small geometry issue in the ifc.js viewer.

[1621203160635-rstbasicsampleproject.ifc.zip](https://github.com/agviegas/web-ifc-viewer/files/6491605/1621203160635-rstbasicsampleproject.ifc.zip)

**Comment by agviegas** [comment]
Hey, would you mind moving this issue to [web-ifc](https://github.com/tomvandig/web-ifc)? This is where we handle geometry generation. Thanks!

**Comment by richardgush** [comment]
Moved to web-ifc
