### ISSUE TITLE
Blazor support for aspnet core and Net5 integration

### ISSUE THREAD

**Issue by cesarecaoduro** [agviegas/web-ifc-viewer#60]

**Comment by cesarecaoduro** [comment]
Would be interesting to see how the library can be integrated using Blazor Wasm or Blazor server, through JSruntime support.

**Comment by agviegas** [comment]
Hey! This sounds great and we are up for it, but right now we are implementing general functionality of the library. Once the read/ write logic is complete, we'll get into this specific implementations. In the meantime, feel free to drop a PR yourself! 😄

**Comment by cesarecaoduro** [comment]
Already on it and almost working
![2021-06-08 09_14_46-TestIFCJsWebapp (Running) - Microsoft Visual Studio](https://user-images.githubusercontent.com/26373891/121098816-03107280-c83a-11eb-9328-fdda19b27534.jpg)

**Comment by cesarecaoduro** [comment]
Can you see something strange? It looks like this is the last step but the loader doesn't work.
I had to manually change some of the path to suite the Blazor arrangement.
![2021-06-08 10_07_06-TestIFCJsWebapp - Microsoft Visual Studio](https://user-images.githubusercontent.com/26373891/121102796-db250d00-c841-11eb-8989-907c2ce0dc96.jpg)

This is the IFCLoader pulled from ThreeJS (5 days ago is the last commit)
![2021-06-08 10_11_34-TestIFCJsWebapp - Microsoft Visual Studio](https://user-images.githubusercontent.com/26373891/121102839-eed07380-c841-11eb-917b-0079fc5b5c42.jpg)

I needed to add a reference also to this js file
![2021-06-08 10_12_08-TestIFCJsWebapp - Microsoft Visual Studio](https://user-images.githubusercontent.com/26373891/121102882-03147080-c842-11eb-8920-25eac5d884b7.jpg)

And finally this is the organization of the folders
![2021-06-08 10_12_54-TestIFCJsWebapp - Microsoft Visual Studio](https://user-images.githubusercontent.com/26373891/121102938-1f181200-c842-11eb-810c-c7015615dd0d.jpg)

and this is the error in the console
![2021-06-08 10_15_24-TestIFCJsWebapp - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/26373891/121103164-9b125a00-c842-11eb-8026-f22f5e2dd467.jpg)

**Comment by cesarecaoduro** [comment]
Ok now we talk!
Just some issue with referencing the libraries...
![2021-06-08 15_12_44-TestIFCJsWebapp and 12 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/26373891/121126761-0ae90a80-c86c-11eb-867c-a84e9e20e66a.jpg)
