### ISSUE TITLE
 IFC files with coordinates away from the zero mute point do not render

### ISSUE THREAD

**Issue by Maiconjss** [agviegas/web-ifc-viewer#61]
Difference between files with coordinates near the point and far:

Close to the zero point:
![filegeoOK](https://user-images.githubusercontent.com/57241193/119267346-9738d380-bbc4-11eb-9c78-f2e3752390fa.PNG)

Far to zero point:
![filegeoNOOK](https://user-images.githubusercontent.com/57241193/119267425-e67f0400-bbc4-11eb-81f0-571b38e4a987.PNG)

**Comment by harrycollin** [comment]
Hi @Maiconjss, this should be a simple fix. I'll make a PR for it now.
