### ISSUE TITLE
Demo project run error

### ISSUE THREAD

**Issue by Mistrymm7** [agviegas/web-ifc-viewer#66]
I am setting up the project and following steps listed in the guide. https://agviegas.github.io/ifcjs-docs/#/guide

I am receiving error shown in image for npm run build

![error ifcjs](https://user-images.githubusercontent.com/7644450/120914700-701edf00-c665-11eb-9abb-f84549b7dc1a.PNG)

**Comment by Mistrymm7** [comment]
I copy pasted two lines in package.json but now I am getting new error as shown in image.
![error 2](https://user-images.githubusercontent.com/7644450/120914859-50d48180-c666-11eb-902e-c71135876d24.PNG)

**Comment by agviegas** [comment]
Hey, it looks like you are missing a comma on line 7 in the last image.

**Comment by vegarringdal** [comment]
You are missing a comma..

![image](https://user-images.githubusercontent.com/2901416/120928966-46a69780-c6e7-11eb-911d-454aa363d371.png)
