### ISSUE TITLE
unexpected profile type errors

### ISSUE THREAD

**Issue by cesarecaoduro** [agviegas/web-ifc-viewer#67]
The IFX is exported from Revit 2021 as IFC2x3 
![2021-06-07 13_34_35-Autodesk Revit 2021 1 -  SGWS3-JHSW-3000-RS-M3D-003430 rvt - 3D View_ Navis Expo](https://user-images.githubusercontent.com/26373891/120955629-27664380-c795-11eb-9a38-2d920d466894.jpg)

![2021-06-07 13_32_04-Settings](https://user-images.githubusercontent.com/26373891/120955585-0a317500-c795-11eb-9c09-9db04a14d856.jpg)

**Comment by cesarecaoduro** [comment]
I believe there should be also a zoom extents functionality for the objects that are not close to the origin but in world coordinates.
I have tried to isolate only one object to make it easier to translate, it looks that there is something now but maybe it's far from the origin and I can't see it
![2021-06-07 13_49_26-Inbox - Cesare Caoduro@aecom com - Outlook](https://user-images.githubusercontent.com/26373891/120956593-377f2280-c797-11eb-862c-05e2325861f8.jpg)

**Comment by agviegas** [comment]
Hey, can you provide us with the model to test? There's actually a [zoom extent](https://github.com/agviegas/web-ifc-viewer/blob/c73e3895a4636ce0fd041283a93c5bd2ab6e8bd0/viewer/src/core/viewer.ts#L112) functionality implemented already. It's a first version but it should work for this case!

**Comment by cesarecaoduro** [comment]
> Hey, can you provide us with the model to test? There's actually a [zoom extent](https://github.com/agviegas/web-ifc-viewer/blob/c73e3895a4636ce0fd041283a93c5bd2ab6e8bd0/viewer/src/core/viewer.ts#L112) functionality implemented already. It's a first version but it should work for this case!

There you go with an example
[RW.zip](https://github.com/agviegas/web-ifc-viewer/files/6612431/RW.zip)
Thanks!

**Comment by agviegas** [comment]
Hey, I managed to reproduce this. Would you mind closing this issue and bringing this to web-ifc? There is where we handle geometry generation. Thanks!
