### ISSUE TITLE
Uncaught ReferenceError: loadBcf is not defined

### ISSUE THREAD

**Issue by baldash** [agviegas/web-ifc-viewer#68]
Hi all, 

As the tile says, when running the example I'm getting:  

```
Uncaught ReferenceError: loadBcf is not defined
    at main.js:58285
    at main.js:58313
```

I'm running on Opera but I don't think this the problem because it works fine when I'm running the online one. Any ideas ?

**Comment by agviegas** [comment]
Hey, can you provide us with the code to take a look?

**Comment by baldash** [comment]
```
const bcfInputElement = document.createElement('input');
bcfInputElement.setAttribute('type', 'file');
bcfInputElement.classList.add('hidden');
bcfInputElement.addEventListener('change', loadBcf, false); <-- error thrown here
document.body.appendChild(bcfInputElement);
```

This causes the side menu to not appear, thus preventing me from importing ifc files in the view. Am i missing some resources ? I ran  `npm run init-repo` and npm / yarn install in all folders before running the server

**Comment by agviegas** [comment]
I have just realized that the bcp importer / exporter is not implemented in the vanilla JS example. If you comment those lines, you should have it working. We will implement it asap!

**Comment by baldash** [comment]
Just tried it and it works perfectly, thanks !

Asking just for information, is it possible to display all elements and view their properties directly in the web-ifc view ?

**Comment by baldash** [comment]
The IFC is well loaded but it seems I can't really select the different elements composing the IFC.

I get this error after loading the IFC:  
```
DevTools failed to load source map: Could not load content for http://172.31.202.131:5000/build/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Maybe it's related ?

**Comment by baldash** [comment]
Ok I fixed the error but still not able to select elements, did I missed something ? I'm loading the IFC example file "IFC Schependomlaan.ifc"

**Comment by agviegas** [comment]
We will push a new version these days. Once that happens, this should get solved!

**Comment by baldash** [comment]
Nice thanks for the info !
