### ISSUE TITLE
Make all arguments that require THREE.Color also accept an hexadecimal number

### ISSUE THREAD

**Issue by agviegas** [agviegas/web-ifc-viewer#75]
This way, users wont be forced to import THREE.

**Comment by piliadis** [comment]
Hi there,
Just wanted to note that `IfcViewerAPI` receives a `ViewerOptions` object in which the `backgroundColor` property is a three Color. I tried several ways to pass a simple hex code with no luck. Am I missing something?
Thanks in advance!

**Comment by agviegas** [comment]
Hi!

We are going to officially release the new library [components](https://github.com/ifcjs/components) on September 20. This library will substitute web-ifc-three and web-ifc-viewer. Both WIV and WIT will remain up, but they will be deprecated and won't be maintained any longer.

All our efforts are going towards components now. The API is very similar, so I strongly suggest you make the leap and start using it. You can start using it now (check out the latest alpha version in npm or see the big-restructure branch in the repo. If you still face this issue with it, you can open an issue there and we'll take a look.

Cheers!
